version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    network_mode: bridge
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/Container/application/radarr/config:/config
      - /share/Movies:/movies #optional
      - /share/Téléchargements:/downloads #optional
      - /share:/share
    ports:
      - 7878:7878
    restart: unless-stopped
