version: "3"
services:
  dashy:
    container_name: Dashy
    network_mode: bridge
    # Pull latest image from DockerHub
    image: lissy93/dashy

    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .

    # You can also use an image with a different tag, or pull from a different registry, e.g:
    # image: ghcr.io/lissy93/dashy or image: lissy93/dashy:3.0.0

    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /share/container/application/dashy/item-icons:/app/user-data/item-icons/
      - type: bind
        source: /share/Container/application/dashy/user-data/conf.yml
        target: /app/user-data/conf.yml
      

    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 5555:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
